CREATE TABLE IF NOT EXISTS Team_Season(team VARCHAR(30) NOT NULL, season VARCHAR(30) NOT NULL, wins INT NOT NULL, losses INT NOT NULL, PRIMARY KEY (team, season));

CREATE TABLE IF NOT EXISTS Offensive(team VARCHAR(30) NOT NULL, season VARCHAR(10) NOT NULL, goals INT NOT NULL, attempts INT NOT NULL, shots_on_target INT NOT NULL, headed_goals INT NOT NULL, freekick_goals INT NOT NULL, goals_outside_box INT NOT NULL, big_chance_missed INT NOT NULL, penalty_goals INT NOT NULL, goals_inside_box INT NOT NULL, goals_fast_break INT NOT NULL, PRIMARY KEY (team, season), FOREIGN KEY (team, season) REFERENCES Team_Season(team, season) ON DELETE CASCADE);

CREATE TABLE IF NOT EXISTS Possesion(team VARCHAR(30) NOT NULL, season VARCHAR(10) NOT NULL, total_passes INT NOT NULL, total_long_balls INT NOT NULL , total_crosses INT NOT NULL, touches INT NOT NULL, total_offsides INT NOT NULL, total_through_balls INT NOT NULL, backwards_passes INT NOT NULL, corner_taken INT NOT NULL , dispossesed INT NOT NULL, PRIMARY KEY (team, season), FOREIGN KEY (team, season) REFERENCES Team_Season(team, season) ON DELETE CASCADE);

CREATE TABLE IF NOT EXISTS Defensive(team VARCHAR(30) NOT NULL, season VARCHAR(10) NOT NULL, total_yellow_cards INT NOT NULL, clean_sheets INT NOT NULL , outfielder_blocks INT NOT NULL , total_tackles INT NOT NULL , total_clearance INT NOT NULL , own_goals INT NOT NULL , penalty_goal_conceded INT NOT NULL , total_red_cards INT NOT NULL , goals_conceded INT NOT NULL , interceptions INT NOT NULL , last_man_tackles INT NOT NULL , headed_clearance INT NOT NULL , penalty_conceded  INT NOT NULL , clearance_off_line INT NOT NULL , PRIMARY KEY (team, season), FOREIGN KEY (team, season) REFERENCES Team_Season(team, season) ON DELETE CASCADE);

CREATE TABLE IF NOT EXISTS Goalkeeper(team VARCHAR(30) NOT NULL, season VARCHAR(10) NOT NULL, saves INT NOT NULL , total_high_claim INT NOT NULL , penalty_saves INT NOT NULL , punches INT NOT NULL , PRIMARY KEY (team, season), FOREIGN KEY (team, season) REFERENCES Team_Season(team, season) ON DELETE CASCADE);
