DROP TABLE IF EXISTS Offensive CASCADE;
DROP TABLE IF EXISTS Possesion CASCADE;
DROP TABLE IF EXISTS Defensive CASCADE;
DROP TABLE IF EXISTS Goalkeeper CASCADE;
DROP TABLE IF EXISTS Team_Season CASCADE;
